import logging

from drf_spectacular.utils import OpenApiExample, OpenApiParameter, OpenApiTypes, extend_schema
from rest_framework import status
from rest_framework.decorators import api_view, parser_classes, permission_classes, throttle_classes
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.response import Response

from .permissions import HasAgentApiKeyOrAuthenticated
from .agent_ai.oncology_corpus import load_oncology_corpus_content
from .serializers import (
	AgentQueryResponseSerializer,
	AgentQuerySerializer,
	DomainQueryResponseSerializer,
	ErrorResponseSerializer,
	HealthResponseSerializer,
	MedicalEvidenceSearchResponseSerializer,
	MedicalEvidenceSearchSerializer,
	MedicalFileUploadSerializer,
	MedicalQuerySerializer,
	MedicalTrainingResponseSerializer,
	MedicalTrainingSerializer,
	OncologyEvidenceSearchResponseSerializer,
	OncologyEvidenceSearchSerializer,
	OncologyFileUploadSerializer,
	OncologyQuerySerializer,
	OncologyTrainingResponseSerializer,
	OncologyTrainingSerializer,
)
from .serializers import (  # patient-case additions
	PatientCaseAnalysisResponseSerializer,
	PatientCaseUploadSerializer,
)
from .throttles import AgentAnonRateThrottle, AgentUserRateThrottle


logger = logging.getLogger(__name__)

SERVICES = {}
ONCOLOGY_SAFETY_NOTICE = (
	'This oncology workflow is intended for research support only and does not replace medical diagnosis, '
	'treatment planning, or specialist review.'
)
MEDICAL_SAFETY_NOTICE = (
	'This medical workflow is intended for research support only and does not replace medical diagnosis, '
	'treatment planning, or specialist review.'
)
PATIENT_CASE_SAFETY_NOTICE = (
	'This analysis is generated by an AI system for clinical decision support only. '
	'It does not constitute medical advice, diagnosis, or treatment. '
	'All clinical decisions must be made by qualified licensed healthcare professionals. '
	'PHI has been automatically de-identified per HIPAA Safe Harbor (45 CFR §164.514(b)). '
	'Original patient data is never stored by this system.'
)


def _get_service(domain: str | None = None, subdomain: str | None = None):
	"""Create a single service instance per worker process and domain."""
	service_key = f"{domain or 'general'}::{subdomain or 'default'}"
	if service_key not in SERVICES:
		from .agent_ai.service import CliniGraphService

		SERVICES[service_key] = CliniGraphService(domain=domain, subdomain=subdomain)
	return SERVICES[service_key]


def _validation_error_response(serializer):
	return Response(
		{'error': 'invalid payload', 'detail': serializer.errors},
		status=status.HTTP_400_BAD_REQUEST,
	)


def _agent_failure_response(request_id: str, user_id: str):
	logger.exception('agent execution failed request_id=%s user_id=%s', request_id, user_id)
	return Response(
		{
			'error': 'agent execution failed',
			'request_id': request_id,
		},
		status=status.HTTP_500_INTERNAL_SERVER_ERROR,
	)


@extend_schema(
	operation_id='health',
	description='Health check endpoint used by local automation and uptime checks.',
	responses={200: HealthResponseSerializer},
	auth=[],
)
@api_view(['GET'])
def health(request):
	"""Lightweight health endpoint used by automation and local smoke tests."""
	return Response({'status': 'ok', 'framework': 'django'})


@extend_schema(
	operation_id='agent_query',
	description='Execute AgentAI and return an answer. Authenticate with JWT bearer token or X-API-Key.',
	request=AgentQuerySerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: AgentQueryResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Agent Query Example',
			value={'question': 'What is our refund policy?', 'user_id': 'u-123'},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def agent_query(request):
	"""Run the default AgentAI graph and return answer + cache metadata."""
	serializer = AgentQuerySerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	question = payload['question']
	user_id = payload.get('user_id', 'anonymous')
	history = payload.get('conversation_history') or []
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service()
		if history:
			result = service.ask_with_history(question=question, conversation_history=history, user_id=user_id)
		else:
			result = service.ask(question=question, user_id=user_id)
		return Response(
			{
				'answer': result.answer,
				'cache_hit': result.cache_hit,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		return _agent_failure_response(request_id=request_id, user_id=user_id)


@extend_schema(
	operation_id='oncology_train',
	description='Ingest an oncology knowledge corpus into the vector store for later oncology-focused retrieval.',
	request=OncologyTrainingSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: OncologyTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_train(request):
	"""Ingest oncology documents into the knowledge base for domain-scoped retrieval.

	Supports ingestion strategies:
	- upsert: deterministic id update per source
	- batch-dedup: removes duplicates in current payload
	- versioned: appends @version tag to source keys
	"""
	serializer = OncologyTrainingSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	subdomain = payload.get('subdomain') or None
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain='oncology', subdomain=subdomain)
		result = service.ingest_documents(
			documents=payload['documents'],
			domain='oncology',
			subdomain=subdomain,
			dedup_mode=payload.get('dedup_mode', 'upsert'),
			version_tag=payload.get('version_tag') or None,
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('oncology ingestion failed request_id=%s', request_id)
		return Response(
			{
				'error': 'oncology ingestion failed',
				'request_id': request_id,
			},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='oncology_query',
	description='Run an oncology-focused retrieval workflow over the oncology corpus. Research support only.',
	request=OncologyQuerySerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: DomainQueryResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Oncology Query Example',
			value={'question': 'Summarize common biomarkers for lung cancer research.', 'user_id': 'researcher-1'},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_query(request):
	"""Run the oncology-specific AgentAI graph and include a medical safety notice."""
	serializer = OncologyQuerySerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	question = payload['question']
	user_id = payload.get('user_id', 'anonymous')
	subdomain = payload.get('subdomain') or None
	history = payload.get('conversation_history') or []
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain='oncology', subdomain=subdomain)
		if history:
			result = service.ask_with_history(question=question, conversation_history=history, user_id=user_id)
		else:
			result = service.ask(question=question, user_id=user_id)
		return Response(
			{
				'answer': result.answer,
				'cache_hit': result.cache_hit,
				'request_id': request_id,
				'domain': 'oncology',
				'subdomain': subdomain or '',
				'safety_notice': ONCOLOGY_SAFETY_NOTICE,
				'citations': result.citations or [],
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		return _agent_failure_response(request_id=request_id, user_id=user_id)


@extend_schema(
	operation_id='oncology_evidence_search',
	description='Retrieve top oncology evidence documents with optional cancer type and biomarker filters.',
	request=OncologyEvidenceSearchSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: OncologyEvidenceSearchResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Oncology Evidence Search Example',
			value={'query': 'EGFR resistance pathways', 'cancer_type': 'lung cancer', 'biomarker': 'EGFR', 'max_results': 3},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_evidence_search(request):
	"""Return structured oncology evidence snippets with optional metadata filters.

	Filters supported:
	- subdomain
	- cancer_type
	- biomarker
	- evidence_type
	- publication year range
	- optional rerank strategy
	"""
	serializer = OncologyEvidenceSearchSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	subdomain = payload.get('subdomain') or None

	try:
		service = _get_service(domain='oncology', subdomain=subdomain)
		result = service.search_evidence(
			query=payload['query'],
			max_results=payload['max_results'],
			cancer_type=payload.get('cancer_type') or None,
			biomarker=payload.get('biomarker') or None,
			subdomain=subdomain,
			evidence_type=payload.get('evidence_type') or None,
			publication_year_from=payload.get('publication_year_from'),
			publication_year_to=payload.get('publication_year_to'),
			rerank=payload.get('rerank', True),
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'query': payload['query'],
				'evidence': result.evidence,
				'request_id': request_id,
				'safety_notice': ONCOLOGY_SAFETY_NOTICE,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('oncology evidence search failed request_id=%s', request_id)
		return Response(
			{
				'error': 'oncology evidence search failed',
				'request_id': request_id,
			},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='oncology_upload',
	description='Upload a JSON, CSV, or TXT oncology corpus file for ingestion into a selected oncology subdomain.',
	request=OncologyFileUploadSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: OncologyTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_upload(request):
	"""Upload and ingest an oncology corpus file directly through the API."""
	serializer = OncologyFileUploadSerializer(data=request.data)
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	uploaded_file = payload['file']
	subdomain = payload.get('subdomain') or None

	try:
		documents = load_oncology_corpus_content(uploaded_file.name, uploaded_file.read())
		service = _get_service(domain='oncology', subdomain=subdomain)
		result = service.ingest_documents(
			documents=documents,
			domain='oncology',
			subdomain=subdomain,
			dedup_mode='batch-dedup',
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except ValueError as exc:
		return Response(
			{'error': 'invalid upload file', 'detail': str(exc), 'request_id': request_id},
			status=status.HTTP_400_BAD_REQUEST,
		)
	except Exception:
		logger.exception('oncology upload failed request_id=%s', request_id)
		return Response(
			{'error': 'oncology upload failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='medical_train_v2',
	description='Ingest a medical corpus for any disease domain. V2 generic endpoint.',
	request=MedicalTrainingSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: MedicalTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_train(request):
	"""V2 generic medical ingestion endpoint that supports any disease domain."""
	serializer = MedicalTrainingSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.ingest_documents(
			documents=payload['documents'],
			domain=domain,
			subdomain=subdomain,
			dedup_mode=payload.get('dedup_mode', 'upsert'),
			version_tag=payload.get('version_tag') or None,
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('medical ingestion failed request_id=%s domain=%s', request_id, domain)
		return Response(
			{'error': 'medical ingestion failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='medical_query_v2',
	description='Run a domain-scoped medical retrieval workflow for any disease area. V2 generic endpoint.',
	request=MedicalQuerySerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: DomainQueryResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_query(request):
	"""V2 generic medical query endpoint for any configured domain and subdomain."""
	serializer = MedicalQuerySerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	question = payload['question']
	user_id = payload.get('user_id', 'anonymous')
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None
	history = payload.get('conversation_history') or []
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		if history:
			result = service.ask_with_history(question=question, conversation_history=history, user_id=user_id)
		else:
			result = service.ask(question=question, user_id=user_id)
		return Response(
			{
				'answer': result.answer,
				'cache_hit': result.cache_hit,
				'request_id': request_id,
				'domain': domain,
				'subdomain': subdomain or '',
				'safety_notice': MEDICAL_SAFETY_NOTICE,
				'citations': result.citations or [],
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		return _agent_failure_response(request_id=request_id, user_id=user_id)


@extend_schema(
	operation_id='medical_evidence_search_v2',
	description='Retrieve structured evidence for any disease domain with metadata filters. V2 generic endpoint.',
	request=MedicalEvidenceSearchSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: MedicalEvidenceSearchResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_evidence_search(request):
	"""V2 generic evidence search endpoint with condition/marker filters."""
	serializer = MedicalEvidenceSearchSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None

	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.search_evidence(
			query=payload['query'],
			max_results=payload['max_results'],
			condition=payload.get('condition') or None,
			marker=payload.get('marker') or None,
			cancer_type=payload.get('cancer_type') or None,
			biomarker=payload.get('biomarker') or None,
			subdomain=subdomain,
			evidence_type=payload.get('evidence_type') or None,
			publication_year_from=payload.get('publication_year_from'),
			publication_year_to=payload.get('publication_year_to'),
			rerank=payload.get('rerank', True),
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'query': payload['query'],
				'evidence': result.evidence,
				'request_id': request_id,
				'safety_notice': MEDICAL_SAFETY_NOTICE,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('medical evidence search failed request_id=%s domain=%s', request_id, domain)
		return Response(
			{'error': 'medical evidence search failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='medical_upload_v2',
	description='Upload and ingest a generic medical corpus file for any disease domain. V2 generic endpoint.',
	request=MedicalFileUploadSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: MedicalTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_upload(request):
	"""V2 generic upload endpoint for non-oncology disease corpora."""
	serializer = MedicalFileUploadSerializer(data=request.data)
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	uploaded_file = payload['file']
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None

	try:
		documents = load_oncology_corpus_content(uploaded_file.name, uploaded_file.read())
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.ingest_documents(
			documents=documents,
			domain=domain,
			subdomain=subdomain,
			dedup_mode='batch-dedup',
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except ValueError as exc:
		return Response(
			{'error': 'invalid upload file', 'detail': str(exc), 'request_id': request_id},
			status=status.HTTP_400_BAD_REQUEST,
		)
	except Exception:
		logger.exception('medical upload failed request_id=%s domain=%s', request_id, domain)
		return Response(
			{'error': 'medical upload failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


# ── Patient Case Analysis ────────────────────────────────────────────────────


def _build_case_prompt(clean_text: str, question: str, domain: str) -> str:
	"""
	Build a structured clinical analysis prompt from de-identified patient text.

	The caller guarantees that ``clean_text`` has already been de-identified —
	no PHI should be present before this function is called.
	"""
	base = (
		"You are a clinical decision support system. Analyze the following "
		"de-identified patient case and provide evidence-based recommendations. "
		"Do NOT speculate about or attempt to recover redacted identifiers. "
		f"Focus on clinical findings and treatment options relevant to {domain} medicine.\n\n"
		"== DE-IDENTIFIED PATIENT CASE ==\n"
		f"{clean_text}\n"
		"== END OF CASE ==\n\n"
	)
	if question:
		base += f"Specific clinical question: {question}\n\n"
	base += (
		"Please provide:\n"
		"1. Key clinical findings summary\n"
		"2. Differential diagnoses (ranked by likelihood)\n"
		"3. Evidence-based treatment recommendations (reference specific guidelines or trials)\n"
		"4. Monitoring parameters and follow-up plan\n"
		"5. Red flags or urgent considerations, if any"
	)
	return base


@extend_schema(
	operation_id='patient_case_analyze',
	description=(
		'Upload a patient case document (history, symptoms, labs, imaging reports) and receive '
		'evidence-based clinical recommendations. '
		'All PHI is automatically detected and redacted per HIPAA Safe Harbor '
		'(45 CFR §164.514(b)) before any AI processing. '
		'Original content is never stored — only an anonymised audit record is kept.'
	),
	request=PatientCaseUploadSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: PatientCaseAnalysisResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Patient Case via Text',
			value={
				'text': (
					'Patient presents with 3-week history of dyspnoea on exertion. '
					'History of hypertension and type 2 diabetes. '
					'Echocardiogram: EF 35%. BNP 850 pg/mL. '
					'Medications: metformin 1000 mg BD, lisinopril 10 mg daily.'
				),
				'domain': 'cardiology',
				'question': 'What are the evidence-based treatment options for HFrEF?',
				'user_id': 'clinician-001',
			},
			request_only=True,
		),
		OpenApiExample(
			'Patient Case via File Upload',
			value={
				'domain': 'neurology',
				'user_id': 'clinician-002',
			},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
@permission_classes([HasAgentApiKeyOrAuthenticated])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def patient_case_analyze(request):
	"""
	Analyze a patient case with HIPAA-compliant PHI de-identification.

	Processing pipeline:
	1. Extract text from uploaded file or use provided free text.
	2. Detect and redact all 18 HIPAA Safe Harbor PHI categories.
	3. Build a structured clinical analysis prompt from de-identified text.
	4. Retrieve relevant medical evidence from the knowledge base.
	5. Generate evidence-based recommendations via the LLM.
	6. Persist an audit record (zero PHI stored).
	"""
	import hashlib
	import uuid as _uuid

	from .agent_ai.file_extractor import extract_text
	from .agent_ai.phi_deidentifier import deidentify
	from .models import PatientCaseSession

	serializer = PatientCaseUploadSerializer(data=request.data)
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None
	user_id = payload.get('user_id', 'anonymous')
	question = (payload.get('question') or '').strip()
	request_id = getattr(request, 'request_id', 'n/a')
	source_filename = ''

	# ── Step 1: Extract raw text ─────────────────────────────────────────────
	raw_text = ''
	if payload.get('file'):
		uploaded = payload['file']
		source_filename = uploaded.name
		try:
			raw_text = extract_text(uploaded.name, uploaded.read())
		except ValueError as exc:
			return Response(
				{'error': 'file extraction failed', 'detail': str(exc), 'request_id': request_id},
				status=status.HTTP_400_BAD_REQUEST,
			)
	else:
		raw_text = payload.get('text', '')

	if not raw_text.strip():
		return Response(
			{'error': 'no text content found in the provided input', 'request_id': request_id},
			status=status.HTTP_400_BAD_REQUEST,
		)

	# ── Step 2: HIPAA Safe Harbor de-identification ──────────────────────────
	clean_text, redaction_summary = deidentify(raw_text)
	logger.info(
		'phi_deidentify request_id=%s redactions=%d categories=%s',
		request_id,
		redaction_summary.total_redactions,
		list(redaction_summary.categories.keys()),
	)

	# ── Step 3: One-way hash of original text for audit (no PHI stored) ──────
	text_hash = hashlib.sha256(raw_text.encode('utf-8', errors='replace')).hexdigest()

	# ── Step 4: Build clinical analysis prompt ────────────────────────────────
	clinical_prompt = _build_case_prompt(clean_text, question, domain)

	# ── Step 5: Evidence-based analysis ──────────────────────────────────────
	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.ask(question=clinical_prompt, user_id=user_id)
	except Exception:
		logger.exception('patient_case_analyze failed request_id=%s', request_id)
		return Response(
			{'error': 'analysis failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)

	# ── Step 6: Persist audit record (zero PHI) ───────────────────────────────
	session_id = _uuid.uuid4()
	try:
		PatientCaseSession.objects.create(
			session_id=session_id,
			domain=domain,
			subdomain=subdomain or '',
			text_hash=text_hash,
			redaction_count=redaction_summary.total_redactions,
			redaction_categories=redaction_summary.categories,
			source_filename=source_filename,
			user_id=user_id,
		)
	except Exception:
		# Audit persistence failure must not surface to the caller.
		logger.exception('audit_log_failed request_id=%s session_id=%s', request_id, session_id)

	return Response(
		{
			'session_id': str(session_id),
			'analysis': result.answer,
			'citations': result.citations or [],
			'redaction_summary': redaction_summary.as_dict(),
			'domain': domain,
			'safety_notice': PATIENT_CASE_SAFETY_NOTICE,
			'request_id': request_id,
		},
		status=status.HTTP_200_OK,
	)
