import logging

from django.db.models import Max, Q
from django.utils import timezone

from drf_spectacular.utils import OpenApiExample, OpenApiParameter, OpenApiTypes, extend_schema
from rest_framework import status
from rest_framework.decorators import api_view, parser_classes, permission_classes, throttle_classes
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .permissions import HasActiveEntitlement, HasLlmAccessOrApiKey, IsTenantClinicianOrAbove
from .agent_ai.oncology_corpus import load_oncology_corpus_content
from .models import AgentChatHighlight, AgentChatMessage, AgentChatSession
from .serializers import (
	AgentChatHighlightCreateSerializer,
	AgentChatHighlightSerializer,
	AgentChatSessionDetailSerializer,
	AgentChatSessionListResponseSerializer,
	AgentChatSessionSummarySerializer,
	AgentChatSessionCreateSerializer,
	AgentChatMessageCreateSerializer,
	AgentChatMessageSerializer,
	AgentQueryResponseSerializer,
	AgentQuerySerializer,
	DomainQueryResponseSerializer,
	ErrorResponseSerializer,
	HealthResponseSerializer,
	MedicalEvidenceSearchResponseSerializer,
	MedicalEvidenceSearchSerializer,
	MedicalFileUploadSerializer,
	MedicalQuerySerializer,
	MedicalTrainingResponseSerializer,
	MedicalTrainingSerializer,
	OncologyEvidenceSearchResponseSerializer,
	OncologyEvidenceSearchSerializer,
	OncologyFileUploadSerializer,
	OncologyQuerySerializer,
	OncologyTrainingResponseSerializer,
	OncologyTrainingSerializer,
)
from .serializers import (  # patient-case additions
	PatientCaseAnalysisResponseSerializer,
	PatientCaseUploadSerializer,
)
from .throttles import AgentAnonRateThrottle, AgentUserRateThrottle


logger = logging.getLogger(__name__)

SERVICES = {}
ONCOLOGY_SAFETY_NOTICE = (
	'This oncology workflow is intended for research support only and does not replace medical diagnosis, '
	'treatment planning, or specialist review.'
)
MEDICAL_SAFETY_NOTICE = (
	'This medical workflow is intended for research support only and does not replace medical diagnosis, '
	'treatment planning, or specialist review.'
)
PATIENT_CASE_SAFETY_NOTICE = (
	'This analysis is generated by an AI system for clinical decision support only. '
	'It does not constitute medical advice, diagnosis, or treatment. '
	'All clinical decisions must be made by qualified licensed healthcare professionals. '
	'PHI has been automatically de-identified per HIPAA Safe Harbor (45 CFR §164.514(b)). '
	'Original patient data is never stored by this system.'
)


def _get_service(domain: str | None = None, subdomain: str | None = None):
	"""Create a single service instance per worker process and domain."""
	service_key = f"{domain or 'general'}::{subdomain or 'default'}"
	if service_key not in SERVICES:
		from .agent_ai.service import CliniGraphService

		SERVICES[service_key] = CliniGraphService(domain=domain, subdomain=subdomain)
	return SERVICES[service_key]


def _validation_error_response(serializer):
	return Response(
		{'error': 'invalid payload', 'detail': serializer.errors},
		status=status.HTTP_400_BAD_REQUEST,
	)


def _agent_failure_response(request_id: str, user_id: str):
	logger.exception('agent execution failed request_id=%s user_id=%s', request_id, user_id)
	return Response(
		{
			'error': 'agent execution failed',
			'request_id': request_id,
		},
		status=status.HTTP_500_INTERNAL_SERVER_ERROR,
	)


@extend_schema(
	operation_id='health',
	description='Health check endpoint used by local automation and uptime checks.',
	responses={200: HealthResponseSerializer},
	auth=[],
)
@api_view(['GET'])
def health(request):
	"""Lightweight health endpoint used by automation and local smoke tests."""
	return Response({'status': 'ok', 'framework': 'django'})


@extend_schema(
	operation_id='agent_query',
	description='Execute AgentAI and return an answer. Authenticate with JWT bearer token or X-API-Key.',
	request=AgentQuerySerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: AgentQueryResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Agent Query Example',
			value={'question': 'What is our refund policy?', 'user_id': 'u-123'},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def agent_query(request):
	"""Run the default AgentAI graph and return answer + cache metadata."""
	serializer = AgentQuerySerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	question = payload['question']
	user_id = payload.get('user_id', 'anonymous')
	history = payload.get('conversation_history') or []
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service()
		if history:
			result = service.ask_with_history(question=question, conversation_history=history, user_id=user_id)
		else:
			result = service.ask(question=question, user_id=user_id)
		return Response(
			{
				'answer': result.answer,
				'cache_hit': result.cache_hit,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		return _agent_failure_response(request_id=request_id, user_id=user_id)


@extend_schema(
	operation_id='oncology_train',
	description='Ingest an oncology knowledge corpus into the vector store for later oncology-focused retrieval.',
	request=OncologyTrainingSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: OncologyTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_train(request):
	"""Ingest oncology documents into the knowledge base for domain-scoped retrieval.

	Supports ingestion strategies:
	- upsert: deterministic id update per source
	- batch-dedup: removes duplicates in current payload
	- versioned: appends @version tag to source keys
	"""
	serializer = OncologyTrainingSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	subdomain = payload.get('subdomain') or None
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain='oncology', subdomain=subdomain)
		result = service.ingest_documents(
			documents=payload['documents'],
			domain='oncology',
			subdomain=subdomain,
			dedup_mode=payload.get('dedup_mode', 'upsert'),
			version_tag=payload.get('version_tag') or None,
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('oncology ingestion failed request_id=%s', request_id)
		return Response(
			{
				'error': 'oncology ingestion failed',
				'request_id': request_id,
			},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='oncology_query',
	description='Run an oncology-focused retrieval workflow over the oncology corpus. Research support only.',
	request=OncologyQuerySerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: DomainQueryResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Oncology Query Example',
			value={'question': 'Summarize common biomarkers for lung cancer research.', 'user_id': 'researcher-1'},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_query(request):
	"""Run the oncology-specific AgentAI graph and include a medical safety notice."""
	serializer = OncologyQuerySerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	question = payload['question']
	user_id = payload.get('user_id', 'anonymous')
	subdomain = payload.get('subdomain') or None
	history = payload.get('conversation_history') or []
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain='oncology', subdomain=subdomain)
		if history:
			result = service.ask_with_history(question=question, conversation_history=history, user_id=user_id)
		else:
			result = service.ask(question=question, user_id=user_id)
		return Response(
			{
				'answer': result.answer,
				'cache_hit': result.cache_hit,
				'request_id': request_id,
				'domain': 'oncology',
				'subdomain': subdomain or '',
				'safety_notice': ONCOLOGY_SAFETY_NOTICE,
				'citations': result.citations or [],
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		return _agent_failure_response(request_id=request_id, user_id=user_id)


@extend_schema(
	operation_id='oncology_evidence_search',
	description='Retrieve top oncology evidence documents with optional cancer type and biomarker filters.',
	request=OncologyEvidenceSearchSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: OncologyEvidenceSearchResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Oncology Evidence Search Example',
			value={'query': 'EGFR resistance pathways', 'cancer_type': 'lung cancer', 'biomarker': 'EGFR', 'max_results': 3},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_evidence_search(request):
	"""Return structured oncology evidence snippets with optional metadata filters.

	Filters supported:
	- subdomain
	- cancer_type
	- biomarker
	- evidence_type
	- publication year range
	- optional rerank strategy
	"""
	serializer = OncologyEvidenceSearchSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	subdomain = payload.get('subdomain') or None

	try:
		service = _get_service(domain='oncology', subdomain=subdomain)
		result = service.search_evidence(
			query=payload['query'],
			max_results=payload['max_results'],
			cancer_type=payload.get('cancer_type') or None,
			biomarker=payload.get('biomarker') or None,
			subdomain=subdomain,
			evidence_type=payload.get('evidence_type') or None,
			publication_year_from=payload.get('publication_year_from'),
			publication_year_to=payload.get('publication_year_to'),
			rerank=payload.get('rerank', True),
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'query': payload['query'],
				'evidence': result.evidence,
				'request_id': request_id,
				'safety_notice': ONCOLOGY_SAFETY_NOTICE,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('oncology evidence search failed request_id=%s', request_id)
		return Response(
			{
				'error': 'oncology evidence search failed',
				'request_id': request_id,
			},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='oncology_upload',
	description='Upload a JSON, CSV, or TXT oncology corpus file for ingestion into a selected oncology subdomain.',
	request=OncologyFileUploadSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: OncologyTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def oncology_upload(request):
	"""Upload and ingest an oncology corpus file directly through the API."""
	serializer = OncologyFileUploadSerializer(data=request.data)
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	uploaded_file = payload['file']
	subdomain = payload.get('subdomain') or None

	try:
		documents = load_oncology_corpus_content(uploaded_file.name, uploaded_file.read())
		service = _get_service(domain='oncology', subdomain=subdomain)
		result = service.ingest_documents(
			documents=documents,
			domain='oncology',
			subdomain=subdomain,
			dedup_mode='batch-dedup',
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except ValueError as exc:
		return Response(
			{'error': 'invalid upload file', 'detail': str(exc), 'request_id': request_id},
			status=status.HTTP_400_BAD_REQUEST,
		)
	except Exception:
		logger.exception('oncology upload failed request_id=%s', request_id)
		return Response(
			{'error': 'oncology upload failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='medical_train_v2',
	description='Ingest a medical corpus for any disease domain. V2 generic endpoint.',
	request=MedicalTrainingSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: MedicalTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_train(request):
	"""V2 generic medical ingestion endpoint that supports any disease domain."""
	serializer = MedicalTrainingSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.ingest_documents(
			documents=payload['documents'],
			domain=domain,
			subdomain=subdomain,
			dedup_mode=payload.get('dedup_mode', 'upsert'),
			version_tag=payload.get('version_tag') or None,
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('medical ingestion failed request_id=%s domain=%s', request_id, domain)
		return Response(
			{'error': 'medical ingestion failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='medical_query_v2',
	description='Run a domain-scoped medical retrieval workflow for any disease area. V2 generic endpoint.',
	request=MedicalQuerySerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: DomainQueryResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_query(request):
	"""V2 generic medical query endpoint for any configured domain and subdomain."""
	serializer = MedicalQuerySerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	question = payload['question']
	user_id = payload.get('user_id', 'anonymous')
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None
	history = payload.get('conversation_history') or []
	request_id = getattr(request, 'request_id', 'n/a')

	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		if history:
			result = service.ask_with_history(question=question, conversation_history=history, user_id=user_id)
		else:
			result = service.ask(question=question, user_id=user_id)
		return Response(
			{
				'answer': result.answer,
				'cache_hit': result.cache_hit,
				'request_id': request_id,
				'domain': domain,
				'subdomain': subdomain or '',
				'safety_notice': MEDICAL_SAFETY_NOTICE,
				'citations': result.citations or [],
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		return _agent_failure_response(request_id=request_id, user_id=user_id)


@extend_schema(
	operation_id='medical_evidence_search_v2',
	description='Retrieve structured evidence for any disease domain with metadata filters. V2 generic endpoint.',
	request=MedicalEvidenceSearchSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: MedicalEvidenceSearchResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_evidence_search(request):
	"""V2 generic evidence search endpoint with condition/marker filters."""
	serializer = MedicalEvidenceSearchSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None

	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.search_evidence(
			query=payload['query'],
			max_results=payload['max_results'],
			condition=payload.get('condition') or None,
			marker=payload.get('marker') or None,
			cancer_type=payload.get('cancer_type') or None,
			biomarker=payload.get('biomarker') or None,
			subdomain=subdomain,
			evidence_type=payload.get('evidence_type') or None,
			publication_year_from=payload.get('publication_year_from'),
			publication_year_to=payload.get('publication_year_to'),
			rerank=payload.get('rerank', True),
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'query': payload['query'],
				'evidence': result.evidence,
				'request_id': request_id,
				'safety_notice': MEDICAL_SAFETY_NOTICE,
			},
			status=status.HTTP_200_OK,
		)
	except Exception:
		logger.exception('medical evidence search failed request_id=%s domain=%s', request_id, domain)
		return Response(
			{'error': 'medical evidence search failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


@extend_schema(
	operation_id='medical_upload_v2',
	description='Upload and ingest a generic medical corpus file for any disease domain. V2 generic endpoint.',
	request=MedicalFileUploadSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: MedicalTrainingResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
)
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def medical_upload(request):
	"""V2 generic upload endpoint for non-oncology disease corpora."""
	serializer = MedicalFileUploadSerializer(data=request.data)
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	request_id = getattr(request, 'request_id', 'n/a')
	uploaded_file = payload['file']
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None

	try:
		documents = load_oncology_corpus_content(uploaded_file.name, uploaded_file.read())
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.ingest_documents(
			documents=documents,
			domain=domain,
			subdomain=subdomain,
			dedup_mode='batch-dedup',
		)
		return Response(
			{
				'domain': result.domain,
				'subdomain': result.subdomain or '',
				'corpus_name': payload['corpus_name'],
				'documents_received': result.documents_received,
				'duplicates_dropped': result.duplicates_dropped,
				'documents_indexed': result.documents_indexed,
				'dedup_mode': result.dedup_mode,
				'version_tag': result.version_tag,
				'request_id': request_id,
			},
			status=status.HTTP_200_OK,
		)
	except ValueError as exc:
		return Response(
			{'error': 'invalid upload file', 'detail': str(exc), 'request_id': request_id},
			status=status.HTTP_400_BAD_REQUEST,
		)
	except Exception:
		logger.exception('medical upload failed request_id=%s domain=%s', request_id, domain)
		return Response(
			{'error': 'medical upload failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)


# ── Patient Case Analysis ────────────────────────────────────────────────────


def _build_case_prompt(clean_text: str, question: str, domain: str) -> str:
	"""
	Build a structured clinical analysis prompt from de-identified patient text.

	The caller guarantees that ``clean_text`` has already been de-identified —
	no PHI should be present before this function is called.
	"""
	base = (
		"You are a clinical decision support system. Analyze the following "
		"de-identified patient case and provide evidence-based recommendations. "
		"Do NOT speculate about or attempt to recover redacted identifiers. "
		f"Focus on clinical findings and treatment options relevant to {domain} medicine.\n\n"
		"== DE-IDENTIFIED PATIENT CASE ==\n"
		f"{clean_text}\n"
		"== END OF CASE ==\n\n"
	)
	if question:
		base += f"Specific clinical question: {question}\n\n"
	base += (
		"Please provide:\n"
		"1. Key clinical findings summary\n"
		"2. Differential diagnoses (ranked by likelihood)\n"
		"3. Evidence-based treatment recommendations (reference specific guidelines or trials)\n"
		"4. Monitoring parameters and follow-up plan\n"
		"5. Red flags or urgent considerations, if any"
	)
	return base


@extend_schema(
	operation_id='patient_case_analyze',
	description=(
		'Upload a patient case document (history, symptoms, labs, imaging reports) and receive '
		'evidence-based clinical recommendations. '
		'All PHI is automatically detected and redacted per HIPAA Safe Harbor '
		'(45 CFR §164.514(b)) before any AI processing. '
		'Original content is never stored — only an anonymised audit record is kept.'
	),
	request=PatientCaseUploadSerializer,
	parameters=[
		OpenApiParameter(
			name='X-API-Key',
			type=OpenApiTypes.STR,
			location=OpenApiParameter.HEADER,
			required=False,
			description='API key alternative to JWT bearer authentication.',
		),
	],
	responses={
		200: PatientCaseAnalysisResponseSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		429: ErrorResponseSerializer,
		500: ErrorResponseSerializer,
	},
	auth=['BearerAuth', 'ApiKeyAuth'],
	examples=[
		OpenApiExample(
			'Patient Case via Text',
			value={
				'text': (
					'Patient presents with 3-week history of dyspnoea on exertion. '
					'History of hypertension and type 2 diabetes. '
					'Echocardiogram: EF 35%. BNP 850 pg/mL. '
					'Medications: metformin 1000 mg BD, lisinopril 10 mg daily.'
				),
				'domain': 'cardiology',
				'question': 'What are the evidence-based treatment options for HFrEF?',
				'user_id': 'clinician-001',
			},
			request_only=True,
		),
		OpenApiExample(
			'Patient Case via File Upload',
			value={
				'domain': 'neurology',
				'user_id': 'clinician-002',
			},
			request_only=True,
		),
	],
)
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
@permission_classes([HasLlmAccessOrApiKey])
@throttle_classes([AgentAnonRateThrottle, AgentUserRateThrottle])
def patient_case_analyze(request):
	"""
	Analyze a patient case with HIPAA-compliant PHI de-identification.

	Processing pipeline:
	1. Extract text from uploaded file or use provided free text.
	2. Detect and redact all 18 HIPAA Safe Harbor PHI categories.
	3. Build a structured clinical analysis prompt from de-identified text.
	4. Retrieve relevant medical evidence from the knowledge base.
	5. Generate evidence-based recommendations via the LLM.
	6. Persist an audit record (zero PHI stored).
	"""
	import hashlib
	import uuid as _uuid

	from .agent_ai.file_extractor import extract_text
	from .agent_ai.phi_deidentifier import deidentify
	from .models import PatientCaseSession

	serializer = PatientCaseUploadSerializer(data=request.data)
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	domain = (payload.get('domain') or 'medical').strip() or 'medical'
	subdomain = payload.get('subdomain') or None
	user_id = payload.get('user_id', 'anonymous')
	question = (payload.get('question') or '').strip()
	request_id = getattr(request, 'request_id', 'n/a')
	source_filename = ''

	# ── Step 1: Extract raw text ─────────────────────────────────────────────
	raw_text = ''
	if payload.get('file'):
		uploaded = payload['file']
		source_filename = uploaded.name
		try:
			raw_text = extract_text(uploaded.name, uploaded.read())
		except ValueError as exc:
			return Response(
				{'error': 'file extraction failed', 'detail': str(exc), 'request_id': request_id},
				status=status.HTTP_400_BAD_REQUEST,
			)
	else:
		raw_text = payload.get('text', '')

	if not raw_text.strip():
		return Response(
			{'error': 'no text content found in the provided input', 'request_id': request_id},
			status=status.HTTP_400_BAD_REQUEST,
		)

	# ── Step 2: HIPAA Safe Harbor de-identification ──────────────────────────
	clean_text, redaction_summary = deidentify(raw_text)
	logger.info(
		'phi_deidentify request_id=%s redactions=%d categories=%s',
		request_id,
		redaction_summary.total_redactions,
		list(redaction_summary.categories.keys()),
	)

	# ── Step 3: One-way hash of original text for audit (no PHI stored) ──────
	text_hash = hashlib.sha256(raw_text.encode('utf-8', errors='replace')).hexdigest()

	# ── Step 4: Build clinical analysis prompt ────────────────────────────────
	clinical_prompt = _build_case_prompt(clean_text, question, domain)

	# ── Step 5: Evidence-based analysis ──────────────────────────────────────
	try:
		service = _get_service(domain=domain, subdomain=subdomain)
		result = service.ask(question=clinical_prompt, user_id=user_id)
	except Exception:
		logger.exception('patient_case_analyze failed request_id=%s', request_id)
		return Response(
			{'error': 'analysis failed', 'request_id': request_id},
			status=status.HTTP_500_INTERNAL_SERVER_ERROR,
		)

	# ── Step 6: Persist audit record (zero PHI) ───────────────────────────────
	session_id = _uuid.uuid4()
	try:
		PatientCaseSession.objects.create(
			session_id=session_id,
			domain=domain,
			subdomain=subdomain or '',
			text_hash=text_hash,
			redaction_count=redaction_summary.total_redactions,
			redaction_categories=redaction_summary.categories,
			source_filename=source_filename,
			user_id=user_id,
		)
	except Exception:
		# Audit persistence failure must not surface to the caller.
		logger.exception('audit_log_failed request_id=%s session_id=%s', request_id, session_id)

	return Response(
		{
			'session_id': str(session_id),
			'analysis': result.answer,
			'citations': result.citations or [],
			'redaction_summary': redaction_summary.as_dict(),
			'domain': domain,
			'safety_notice': PATIENT_CASE_SAFETY_NOTICE,
			'request_id': request_id,
		},
		status=status.HTTP_200_OK,
	)


def _get_chat_session_for_request(request, session_id: str):
	return AgentChatSession.objects.filter(
		session_id=session_id,
		tenant=request.tenant,
		user=request.user,
		is_archived=False,
	).first()


def _parse_positive_int(raw_value, default_value, minimum=0, maximum=200):
	try:
		value = int(raw_value)
	except (TypeError, ValueError):
		return default_value
	if value < minimum:
		return minimum
	if value > maximum:
		return maximum
	return value


def _make_title_from_content(content: str, max_len: int = 72) -> str:
	text = (content or '').strip().replace('\n', ' ')
	while '  ' in text:
		text = text.replace('  ', ' ')
	if not text:
		return 'New chat'
	for delimiter in ('. ', '? ', '! ', '; '):
		idx = text.find(delimiter)
		if idx > 0:
			text = text[:idx + 1]
			break
	title = text[:max_len].strip()
	return title or 'New chat'


def _make_search_snippet(text: str, term: str, max_len: int = 160) -> str:
	body = (text or '').strip()
	needle = (term or '').strip().lower()
	if not body:
		return ''
	if not needle:
		return body[:max_len]
	idx = body.lower().find(needle)
	if idx < 0:
		return body[:max_len]
	half = max_len // 2
	start = max(0, idx - half)
	end = min(len(body), start + max_len)
	if end - start < max_len:
		start = max(0, end - max_len)
	return body[start:end]


@extend_schema(
	operation_id='agent_chat_sessions',
	description='List or create persistent Agent chat sessions for the authenticated user and tenant.',
	request=AgentChatSessionCreateSerializer,
	responses={
		200: AgentChatSessionListResponseSerializer,
		201: AgentChatSessionSummarySerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		402: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
	},
	auth=['BearerAuth'],
)
@api_view(['GET', 'POST'])
@permission_classes([IsAuthenticated, IsTenantClinicianOrAbove, HasActiveEntitlement])
def agent_chat_sessions(request):
	if request.method == 'POST':
		serializer = AgentChatSessionCreateSerializer(data=request.data or {})
		if not serializer.is_valid():
			return _validation_error_response(serializer)
		title = (serializer.validated_data.get('title') or '').strip() or 'New chat'
		session = AgentChatSession.objects.create(
			tenant=request.tenant,
			user=request.user,
			title=title,
		)
		return Response(
			{
				'session_id': session.session_id,
				'title': session.title,
				'updated_at': session.updated_at,
				'last_activity_at': session.last_activity_at,
				'preview': '',
				'highlights_preview': [],
			},
			status=status.HTTP_201_CREATED,
		)

	search = (request.query_params.get('q') or '').strip()
	limit = _parse_positive_int(request.query_params.get('limit'), 30, minimum=1, maximum=100)
	offset = _parse_positive_int(request.query_params.get('offset'), 0, minimum=0, maximum=5000)
	sessions_qs = AgentChatSession.objects.filter(
		tenant=request.tenant,
		user=request.user,
		is_archived=False,
	).annotate(last_message_at=Max('messages__created_at')).order_by('-last_activity_at')

	if search:
		sessions_qs = sessions_qs.filter(
			Q(title__icontains=search)
			| Q(messages__content__icontains=search)
			| Q(highlights__selected_text__icontains=search)
			| Q(highlights__context_snippet__icontains=search)
		).distinct()

	all_sessions = list(sessions_qs[:300])
	needle = search.lower()
	now = timezone.now()

	def session_score(session):
		if not search:
			return 0
		title = (session.title or '').lower()
		highlight_hits = session.highlights.filter(
			Q(selected_text__icontains=search) | Q(context_snippet__icontains=search)
		).count()
		message_hits = session.messages.filter(content__icontains=search).count()
		age_days = max(0.0, (now - session.last_activity_at).total_seconds() / 86400.0)
		recency_bonus = max(0.0, 20.0 - age_days)

		if title.startswith(needle):
			return 100 + (highlight_hits * 2) + message_hits + recency_bonus
		if needle in title:
			return 80 + (highlight_hits * 2) + message_hits + recency_bonus
		if highlight_hits > 0:
			return 60 + (highlight_hits * 2) + message_hits + recency_bonus
		if message_hits > 0:
			return 40 + message_hits + recency_bonus
		return recency_bonus

	if search:
		all_sessions.sort(key=lambda s: (session_score(s), s.last_activity_at), reverse=True)

	total_count = len(all_sessions)
	paged_sessions = all_sessions[offset: offset + limit]

	items = []
	for session in paged_sessions:
		last_message = session.messages.order_by('-created_at', '-id').first()
		highlight_preview_rows = session.highlights.order_by('-created_at', '-id')[:3]
		preview_source = ''
		if search:
			hit = session.highlights.filter(
				Q(selected_text__icontains=search) | Q(context_snippet__icontains=search)
			).order_by('-created_at', '-id').first()
			if hit:
				preview_source = hit.context_snippet or hit.selected_text
		if not preview_source and search:
			message_hit = session.messages.filter(content__icontains=search).order_by('-created_at', '-id').first()
			if message_hit:
				preview_source = message_hit.content
		if not preview_source and last_message:
			preview_source = last_message.content

		items.append(
			{
				'session_id': session.session_id,
				'title': session.title or 'New chat',
				'updated_at': session.updated_at,
				'last_activity_at': session.last_activity_at,
				'preview': _make_search_snippet(preview_source, search),
				'highlights_preview': [
					{
						'highlight_id': h.id,
						'message_id': h.message_id,
						'selected_text': h.selected_text,
						'start_offset': h.start_offset,
						'end_offset': h.end_offset,
						'context_snippet': h.context_snippet,
						'created_at': h.created_at,
					}
					for h in highlight_preview_rows
				],
			}
		)

	return Response(
		{
			'items': items,
			'pagination': {
				'total': total_count,
				'limit': limit,
				'offset': offset,
				'has_more': (offset + limit) < total_count,
			},
		},
		status=status.HTTP_200_OK,
	)


@extend_schema(
	operation_id='agent_chat_session_detail',
	description='Get full message timeline and highlights for one persistent chat session.',
	responses={
		200: AgentChatSessionDetailSerializer,
		401: ErrorResponseSerializer,
		402: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		404: ErrorResponseSerializer,
	},
	auth=['BearerAuth'],
)
@api_view(['GET'])
@permission_classes([IsAuthenticated, IsTenantClinicianOrAbove, HasActiveEntitlement])
def agent_chat_session_detail(request, session_id):
	session = _get_chat_session_for_request(request, session_id=session_id)
	if not session:
		return Response({'error': 'chat session not found'}, status=status.HTTP_404_NOT_FOUND)

	message_limit = _parse_positive_int(request.query_params.get('message_limit'), 80, minimum=1, maximum=500)
	message_offset = _parse_positive_int(request.query_params.get('message_offset'), 0, minimum=0, maximum=20000)
	from_end_raw = (request.query_params.get('from_end') or '1').strip().lower()
	from_end = from_end_raw not in ('0', 'false', 'no')
	all_messages_qs = session.messages.order_by('created_at', 'id')
	total_messages = all_messages_qs.count()

	if from_end:
		# Offset is interpreted from the end when from_end is enabled.
		end_index = max(total_messages - message_offset, 0)
		start_index = max(end_index - message_limit, 0)
		messages = all_messages_qs[start_index:end_index]
		has_more_messages = start_index > 0
		effective_offset = message_offset
	else:
		messages = all_messages_qs[message_offset:message_offset + message_limit]
		has_more_messages = (message_offset + message_limit) < total_messages
		effective_offset = message_offset

	highlights = session.highlights.order_by('-created_at', '-id')
	return Response(
		{
			'session_id': session.session_id,
			'title': session.title or 'New chat',
			'updated_at': session.updated_at,
			'last_activity_at': session.last_activity_at,
			'messages': [
				{
					'message_id': m.id,
					'role': m.role,
					'content': m.content,
					'request_id': m.request_id,
					'created_at': m.created_at,
				}
				for m in messages
			],
			'messages_pagination': {
				'total': total_messages,
				'limit': message_limit,
				'offset': effective_offset,
				'has_more': has_more_messages,
				'from_end': from_end,
			},
			'highlights': [
				{
					'highlight_id': h.id,
					'message_id': h.message_id,
					'selected_text': h.selected_text,
					'start_offset': h.start_offset,
					'end_offset': h.end_offset,
					'context_snippet': h.context_snippet,
					'created_at': h.created_at,
				}
				for h in highlights
			],
		},
		status=status.HTTP_200_OK,
	)


@extend_schema(
	operation_id='agent_chat_messages_create',
	description='Append one message to a persistent chat session.',
	request=AgentChatMessageCreateSerializer,
	responses={
		201: AgentChatMessageSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		402: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		404: ErrorResponseSerializer,
	},
	auth=['BearerAuth'],
)
@api_view(['POST'])
@permission_classes([IsAuthenticated, IsTenantClinicianOrAbove, HasActiveEntitlement])
def agent_chat_messages_create(request, session_id):
	session = _get_chat_session_for_request(request, session_id=session_id)
	if not session:
		return Response({'error': 'chat session not found'}, status=status.HTTP_404_NOT_FOUND)

	serializer = AgentChatMessageCreateSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	message = AgentChatMessage.objects.create(
		chat_session=session,
		role=payload['role'],
		content=payload['content'],
		request_id=payload.get('request_id', ''),
	)

	if message.role == AgentChatMessage.Role.ASSISTANT and session.title.strip() in ('', 'New chat'):
		session.title = _make_title_from_content(payload['content'])

	session.last_activity_at = timezone.now()
	session.save(update_fields=['title', 'last_activity_at', 'updated_at'])

	return Response(
		{
			'message_id': message.id,
			'role': message.role,
			'content': message.content,
			'request_id': message.request_id,
			'created_at': message.created_at,
		},
		status=status.HTTP_201_CREATED,
	)


@extend_schema(
	operation_id='agent_chat_highlights_create',
	description='Create highlight for a message by text offsets.',
	request=AgentChatHighlightCreateSerializer,
	responses={
		201: AgentChatHighlightSerializer,
		400: ErrorResponseSerializer,
		401: ErrorResponseSerializer,
		402: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		404: ErrorResponseSerializer,
	},
	auth=['BearerAuth'],
)
@api_view(['POST'])
@permission_classes([IsAuthenticated, IsTenantClinicianOrAbove, HasActiveEntitlement])
def agent_chat_highlights_create(request, session_id):
	session = _get_chat_session_for_request(request, session_id=session_id)
	if not session:
		return Response({'error': 'chat session not found'}, status=status.HTTP_404_NOT_FOUND)

	serializer = AgentChatHighlightCreateSerializer(data=request.data or {})
	if not serializer.is_valid():
		return _validation_error_response(serializer)

	payload = serializer.validated_data
	message = session.messages.filter(id=payload['message_id']).first()
	if not message:
		return Response({'error': 'message not found in session'}, status=status.HTTP_404_NOT_FOUND)

	if payload['end_offset'] > len(message.content):
		return Response({'error': 'highlight offsets out of message bounds'}, status=status.HTTP_400_BAD_REQUEST)

	context_snippet = (payload.get('context_snippet') or '').strip()
	if not context_snippet:
		start = max(payload['start_offset'] - 40, 0)
		end = min(payload['end_offset'] + 40, len(message.content))
		context_snippet = message.content[start:end]

	highlight = AgentChatHighlight.objects.create(
		chat_session=session,
		message=message,
		selected_text=payload['selected_text'],
		start_offset=payload['start_offset'],
		end_offset=payload['end_offset'],
		context_snippet=context_snippet,
		created_by=request.user,
	)

	session.last_activity_at = timezone.now()
	session.save(update_fields=['last_activity_at', 'updated_at'])

	return Response(
		{
			'highlight_id': highlight.id,
			'message_id': highlight.message_id,
			'selected_text': highlight.selected_text,
			'start_offset': highlight.start_offset,
			'end_offset': highlight.end_offset,
			'context_snippet': highlight.context_snippet,
			'created_at': highlight.created_at,
		},
		status=status.HTTP_201_CREATED,
	)


@extend_schema(
	operation_id='agent_chat_highlights_pop',
	description='Undo latest highlight (LIFO) for the current user in a chat session.',
	responses={
		200: OpenApiTypes.OBJECT,
		401: ErrorResponseSerializer,
		402: ErrorResponseSerializer,
		403: ErrorResponseSerializer,
		404: ErrorResponseSerializer,
	},
	auth=['BearerAuth'],
)
@api_view(['DELETE'])
@permission_classes([IsAuthenticated, IsTenantClinicianOrAbove, HasActiveEntitlement])
def agent_chat_highlights_pop(request, session_id):
	session = _get_chat_session_for_request(request, session_id=session_id)
	if not session:
		return Response({'error': 'chat session not found'}, status=status.HTTP_404_NOT_FOUND)

	highlight = session.highlights.filter(created_by=request.user).order_by('-created_at', '-id').first()
	if not highlight:
		return Response({'error': 'no highlights to undo'}, status=status.HTTP_404_NOT_FOUND)

	deleted_id = highlight.id
	highlight.delete()
	session.last_activity_at = timezone.now()
	session.save(update_fields=['last_activity_at', 'updated_at'])

	return Response({'undone_highlight_id': deleted_id}, status=status.HTTP_200_OK)
