{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clinigraph.fullname" . }}-grafana
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "clinigraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "clinigraph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
---
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clinigraph.fullname" . }}-grafana-datasources
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "clinigraph.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ include "clinigraph.fullname" . }}-prometheus:9090
        access: proxy
        isDefault: true
{{- end }}
{{- end }}
