{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clinigraph.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "clinigraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | required "secrets.djangoSecretKey is required" | quote }}
  AGENT_API_KEY: {{ .Values.secrets.agentApiKey | required "secrets.agentApiKey is required" | quote }}
  DJANGO_DB_PASSWORD: {{ .Values.secrets.postgresPassword | required "secrets.postgresPassword is required" | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | default "admin" | quote }}
  JWT_ACCESS_TOKEN_LIFETIME_MINUTES: {{ .Values.secrets.jwtAccessMinutes | default "30" | quote }}
  JWT_REFRESH_TOKEN_LIFETIME_DAYS: {{ .Values.secrets.jwtRefreshDays | default "7" | quote }}
{{- end }}
