# Generated by Django 6.0.3 on 2026-03-20 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCaseSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session ID returned to the requesting client.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(blank=True, default='medical', max_length=64)),
                ('subdomain', models.CharField(blank=True, default='', max_length=128)),
                ('text_hash', models.CharField(blank=True, default='', max_length=64)),
                ('redaction_count', models.IntegerField(default=0)),
                ('redaction_categories', models.JSONField(default=dict, help_text='E.g. {"DATE": 3, "PHONE_FAX": 1}')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('user_id', models.CharField(blank=True, default='anonymous', max_length=128)),
            ],
            options={
                'verbose_name': 'Patient Case Session',
                'verbose_name_plural': 'Patient Case Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
