# Generated by Django 6.0.3 on 2026-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscriptionplan_tenant_securityevent_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='provider',
            field=models.CharField(default='stripe', max_length=32),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='provider_price_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='provider_product_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
