# Generated by Django 6.0.3 on 2026-03-20 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscriptionplan_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('clinician', 'Clinician'), ('auditor', 'Auditor')], default='clinician', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant__name', 'user__username'],
                'indexes': [models.Index(fields=['tenant', 'role'], name='api_tenantm_tenant__88a89e_idx'), models.Index(fields=['user', 'is_active'], name='api_tenantm_user_id_4566ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_user_membership')],
            },
        ),
    ]
