# Generated by Django 6.0.3 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_tenantmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="api_overage_per_1000_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="billing_model",
            field=models.CharField(default="hybrid", max_length=24),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="seat_price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]