# Generated by Django 6.0.3 on 2026-03-20

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_subscriptionplan_billing_model_and_hybrid_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("finalized", "Finalized"), ("paid", "Paid"), ("void", "Void")], default="draft", max_length=16)),
                ("platform_fee_cents", models.PositiveIntegerField(default=0)),
                ("users_overage_cents", models.PositiveIntegerField(default=0)),
                ("api_overage_cents", models.PositiveIntegerField(default=0)),
                ("total_cents", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("api_requests", models.PositiveIntegerField(default=0)),
                ("overage_users", models.PositiveIntegerField(default=0)),
                ("overage_api_requests", models.PositiveIntegerField(default=0)),
                ("external_invoice_id", models.CharField(blank=True, default="", max_length=128)),
                ("meta", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_invoices", to="api.subscription")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="billing_invoices", to="api.tenant")),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="billinginvoice",
            constraint=models.UniqueConstraint(fields=("tenant", "period_start", "period_end"), name="unique_tenant_period_invoice"),
        ),
        migrations.AddIndex(
            model_name="billinginvoice",
            index=models.Index(fields=["tenant", "status", "generated_at"], name="api_billingi_tenant__9e6ea6_idx"),
        ),
    ]
