# Generated by Django 6.0.3 on 2026-03-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_billinginvoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInvoiceLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price_cents", models.PositiveIntegerField(default=0)),
                ("total_price_cents", models.PositiveIntegerField(default=0)),
                ("meta", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="api.billinginvoice")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="billinginvoicelineitem",
            index=models.Index(fields=["invoice", "code"], name="api_billingi_invoice__9bb4b7_idx"),
        ),
    ]
