# Generated by Django 6.0.3 on 2026-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_billinginvoicelineitem'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingevent',
            name='api_billing_provide_47a421_idx',
        ),
        migrations.RenameIndex(
            model_name='billinginvoice',
            new_name='api_billing_tenant__0c60f8_idx',
            old_name='api_billingi_tenant__9e6ea6_idx',
        ),
        migrations.RenameIndex(
            model_name='billinginvoicelineitem',
            new_name='api_billing_invoice_514571_idx',
            old_name='api_billingi_invoice__9bb4b7_idx',
        ),
        migrations.AddConstraint(
            model_name='billingevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id__gt', '')), fields=('provider', 'provider_event_id'), name='unique_billing_event_per_provider'),
        ),
    ]
