# Generated by Django 6.0.3 on 2026-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_billing_event_idempotency_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, help_text='Deadline until service is accessible despite PAST_DUE status.', null=True),
        ),
    ]
