# Generated by Django 6.0.3 on 2026-03-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tenantmembership_role_agentchatsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('billing', 'Billing'), ('clinician', 'Clinician'), ('auditor', 'Auditor')], default='clinician', max_length=16),
        ),
    ]
