# Generated by Django 6.0.3 on 2026-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_failed_payment_count_to_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='tax_cents',
            field=models.PositiveIntegerField(default=0, help_text='Tax / VAT applied on top of the subtotal (platform_fee + overages).'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='tax_rate_bps',
            field=models.PositiveIntegerField(default=0, help_text='Effective tax rate in basis points (2000 = 20%). 0 when no tax applies.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 billing country for tax jurisdiction lookup.', max_length=2),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text='When True, no tax is calculated regardless of jurisdiction.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='VAT registration number or EIN supplied by the tenant.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_region_code',
            field=models.CharField(blank=True, default='', help_text='Sub-national region code (US state, CA province) for finer-grained rates.', max_length=16),
        ),
        migrations.CreateModel(
            name='TaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text="ISO 3166-1 alpha-2 code, e.g. 'DE'.", max_length=2)),
                ('region_code', models.CharField(blank=True, default='', help_text='Sub-national code (US state, CA province). Empty = country-wide.', max_length=16)),
                ('rate_bps', models.PositiveIntegerField(help_text='Tax rate in basis points (10000 = 100%, 2000 = 20%).')),
                ('is_inclusive', models.BooleanField(default=False, help_text='True when the price already includes tax (e.g. EU VAT inclusive pricing).')),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country_code', 'region_code'],
                'indexes': [models.Index(fields=['country_code', 'is_active'], name='api_taxpoli_country_74ab98_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'region_code'), name='unique_tax_policy_jurisdiction')],
            },
        ),
    ]
