# Generated by Django 6.0.3 on 2026-04-10 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_tax_policy_and_tenant_tax_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique job identifier returned to the API caller.', primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
                ('subdomain', models.CharField(blank=True, default='', max_length=128)),
                ('corpus_name', models.CharField(blank=True, default='', max_length=128)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('submitted_by', models.CharField(blank=True, default='anonymous', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingestion Job',
                'verbose_name_plural': 'Ingestion Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='api_ingesti_status_2bb90e_idx')],
            },
        ),
    ]
