# Generated by Django 6.0.3 on 2026-04-10 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ingestionjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('fcm', 'Firebase (Android / Web)'), ('apns', 'Apple Push Notification service (iOS)')], max_length=8)),
                ('token', models.CharField(help_text='FCM registration token or APNs device token. Never log or expose outside push dispatch.', max_length=512)),
                ('device_label', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='api.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['tenant', 'user', 'is_active'], name='api_devicet_tenant__792f9f_idx'), models.Index(fields=['platform', 'is_active'], name='api_devicet_platfor_f3d7f5_idx')],
                'unique_together': {('user', 'tenant', 'token')},
            },
        ),
    ]
