# Generated by Django 6.0.3 on 2026-04-10 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalysisSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, default='medical', max_length=64)),
                ('analysis_text', models.TextField(help_text='AI-generated analysis of de-identified case (no PHI).')),
                ('citations', models.JSONField(default=list)),
                ('safety_notice', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_snapshots', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The originating patient case session (audit record only, no PHI).', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.patientcasesession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_snapshots', to='api.tenant')),
            ],
            options={
                'verbose_name': 'Case Analysis Snapshot',
                'verbose_name_plural': 'Case Analysis Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedContentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('target_type', models.CharField(choices=[('highlight', 'Chat Highlight'), ('case_snapshot', 'Patient Case Snapshot')], max_length=32)),
                ('recipient_emails', models.JSONField(default=list, help_text='List of email addresses this token was sent to (audit trail only).')),
                ('expires_at', models.DateTimeField(help_text='UTC timestamp after which the token is invalid.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('max_views', models.PositiveIntegerField(blank=True, help_text='Maximum number of views allowed. Null = unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='api.caseanalysissnapshot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_tokens', to=settings.AUTH_USER_MODEL)),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='api.agentchathighlight')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_tokens', to='api.tenant')),
            ],
            options={
                'verbose_name': 'Shared Content Token',
                'verbose_name_plural': 'Shared Content Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='caseanalysissnapshot',
            index=models.Index(fields=['tenant', '-created_at'], name='api_caseana_tenant__3a1dee_idx'),
        ),
        migrations.AddIndex(
            model_name='caseanalysissnapshot',
            index=models.Index(fields=['session'], name='api_caseana_session_887b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedcontenttoken',
            index=models.Index(fields=['token'], name='api_sharedc_token_35dfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedcontenttoken',
            index=models.Index(fields=['tenant', '-created_at'], name='api_sharedc_tenant__5c04bd_idx'),
        ),
    ]
